schema {
  query: Query
}

scalar JSON

input OrderByInput {
  direction: String = "asc"
  field: String!
}

type Query {
  dados(limit: Int! = 100, offset: Int! = 0, orderBy: OrderByInput = null, where: JSON = null): [JSON!]!
}