schema {
  query: Query
}

scalar JSON

type Query {
  dados(limit: Int! = 100, offset: Int! = 0): [JSON!]!
  dadosFiltrados(campo: String!, limit: Int! = 100, offset: Int! = 0, valor: String!): [JSON!]!
}